### ISSUE TITLE
Error when using NAV

### ISSUE THREAD

**Issue by lormayna** [AlexxNB/svelte-chota#28]
Hello,
I tried to use NAV in my simple app, but I got this error:

`
bundles src/main.js → public/build/bundle.js...
[!] (plugin svelte) Error: Duplicate slot name "right" in <Nav>
src/App.svelte
Error: Duplicate slot name "right" in <Nav>
    at InlineComponentWrapper.set_slot (/home/xxx/progetti/sm_vote/frontend/node_modules/svelte/src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts:98:10)
    at new SlotTemplateWrapper (/home/xxxx/progetti/sm_vote/frontend/node_modules/svelte/src/compiler/compile/render_dom/wrappers/SlotTemplate.ts:60:15)
    at /home/xxxxx/progetti/sm_vote/frontend/node_modules/svelte/src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts:87:52
    at Array.map (<anonymous>)
    at new InlineComponentWrapper (/home/xxxxx/progetti/sm_vote/frontend/node_modules/svelte/src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts:87:39)
    at new FragmentWrapper (/home/xxxx/progetti/sm_vote/frontend/node_modules/svelte/src/compiler/compile/render_dom/wrappers/Fragment.ts:120:21)
    at new SlotTemplateWrapper (/home/xxxx/progetti/sm_vote/frontend/node_modules/svelte/src/compiler/compile/render_dom/wrappers/SlotTemplate.ts:65:19)
    at /home/xxxx/progetti/sm_vote/frontend/node_modules/svelte/src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts:87:52
    at Array.map (<anonymous>)
    at new InlineComponentWrapper (/home/xxxx/progetti/sm_vote/frontend/node_modules/svelte/src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts:87:39)
`

**Comment by AlexxNB** [comment]
dublicate https://github.com/AlexxNB/svelte-chota/issues/25

**Comment by AlexxNB** [comment]
I'll fix documentation later. Thanks.
